Manuel and I were looking into a problem with applications failing to link (undefined reference to `main') when the .o file containing main was contained in an static library(a '.a' ar archive).  It turns out that due to its single pass nature, GNU ld was failing to pull it into the build.  This sticks a dummy reference to main() into crt0.o, so that when an application is linked with the main() function in a static library, we can be sure that main() actually gets linked in.  -Erik